polls/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns=[
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.create_user, name='register'),
]

polls/pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('polls/', include('polls.urls', namespace="polls")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

polls/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('list/', views.polls_list, name='list'),
    path('home/about/', views.about, name='about'),
    path('users/', views.user_list, name='user_list'),
    path('list/about/', views.about, name='add'),
    path('list/user/', views.list_by_user, name='list_by_user'),
    path('add/', views.polls_add, name='add'),
    path('edit/<int:poll_id>/', views.polls_edit, name='edit'),
    path('delete/<int:poll_id>/', views.polls_delete, name='delete_poll'),
    path('end/<int:poll_id>/', views.endpoll, name='end_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name='add_choice'),
    path('edit/choice/<int:choice_id>/', views.choice_edit, name='choice_edit'),
    path('delete/choice/<int:choice_id>/',
         views.choice_delete, name='choice_delete'),
    path('<int:poll_id>/', views.poll_detail, name='detail'),
    path('<int:poll_id>/vote/', views.poll_vote, name='vote'),
]

polls/templates/includes/nav.html
{% block custom_css %}
<style>
    .image1 {
        height: 20px;
        width: 24px;

    }
</style>
{% endblock custom_css %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Shopon | Products</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/pricing/">



  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>



  <!-- Custom styles for this template -->
  <link href="pricing.css" rel="stylesheet">
</head>

<body>
  <nav  class="navbar bg-body-tertiary">
    <div class="text-center">
        <h1 style=" color: blue; font-size: smaller;"></h1>


    </div>
  </nav>
  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check" viewBox="0 0 16 16">
      <title>Check</title>
      <path
        d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
    </symbol>
  </svg>


  <div class="container py-3">
    <header>
      <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-toggles" viewBox="0 0 16 16">
          <path d="M4.5 9a3.5 3.5 0 1 0 0 7h7a3.5 3.5 0 1 0 0-7h-7zm7 6a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zm-7-14a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zm2.45 0A3.49 3.49 0 0 1 8 3.5 3.49 3.49 0 0 1 6.95 6h4.55a2.5 2.5 0 0 0 0-5H6.95zM4.5 0h7a3.5 3.5 0 1 1 0 7h-7a3.5 3.5 0 1 1 0-7z"/>
        </svg>
          <span style="color: blue ; font-size: 5rem; font-weight: bold;"  class="fs-4">LIU | WEB_VOTE</span>
        </a>
        <form style="margin-left: 100px; text-align: center;" class="d-flex" role="search" action="{% url 'polls:list' %}">
          <input type="search" class="form-control" name="search" placeholder="Search" value={{ search_term }}>
          <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          
          <a class="btn btn-outline-warning  me-3 py-2 text-brown " href="{% url 'home' %}">Home</a>
          <a class="btn btn-outline-warning" href="{% url 'polls:list' %}">Elections </a>

          
          
          {% if request.user.is_authenticated %}
          <div class="dropdown" style="margin-left: 20px;">
            <button class="btn btn-danger dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#"><b>Read more</b></a></li>
              <li><a class="dropdown-item" href=""><b>Online</b></a></li>
              {% if request.user.is_staff %}
               <li><a class="dropdown-item" href="{% url 'accounts:register' %}"> <b>Register User</b> </a></li>
               <li><a class="dropdown-item" href="{% url 'polls:user_list' %}"><b>View all users</b></a></li>

              {% endif %}
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"> <b> Logout</b> </a></li>
            </ul>
          </div>  

          {% else %}
          <a class="me-3 ml-3 py-2 text-dark text-decoration-none" href="{% url 'polls:about' %}"> About</a>
          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'accounts:login' %}">Login</a>

          {% endif %}
          
          
</nav>
      </div>

      
    </header>


  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>



</body>

</html>
    {% endblock %}